### ISSUE TITLE
Problem with Locales such as :pt-BR

### ISSUE THREAD

**Issue by erantone** [sunny/route_localize#2]
Hello!

This gem does not seem to support locales such as :pt-BR:

gems/actionpack-4.1.9/lib/action_dispatch/routing/route_set.rb:434:in `add_route': Invalid route name: 'treatment_pt-BR' (ArgumentError)
gems/route_localize-ab80677a0929/lib/route_localize/extensions.rb:6:in `block in add_route_with_locale'

**Comment by sunny** [comment]
Indeed! Would you suggest the route name in that case to be `treatment_pt_br`?

**Comment by erantone** [comment]
Yes, treatment_pt_br would be the best bet. I've done a quick dirty fix on a local repo to work like that.

**Comment by sunny** [comment]
Cool! Would you mind creating a PR or sharing your fix?

**Comment by sunny** [comment]
Hey @erantone, would you mind pushing your changes to your repo so that we can fix this for everybody?
